spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sql_slow?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
sql:
  slow:
    mirror:
      analysisSwitch: true
      onlyCheckOnce: true
      checkInterval: 300000
##      exceptSqlIds: com.cong.example.mapper.TaskMapper.selectList,com.cong.example.mapper.TaskMapper.xxx
      sqlType: SELECT,UPDATE
      outModel: LOG
      outputClass: com.cong.example.out.MySqlScoreResultOutService
